[workspace]
channels = ["conda-forge"]
name = "luminaire-legacy"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
#FIXME: more recent python requires some changes to roast; ast.Num no longer exists
python = ">=3.8.0,<3.9"

[pypi-dependencies]
gitman = ">=3.1, <4"
